development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://mmhmfzrzsbpteu:PZxnW68uK6q60E4nz_16zbTTo4@ec2-23-23-76-90.compute-1.amazonaws.com:5432/dfk8p02l342pio
